### ISSUE TITLE
Commander examples add an entry to the world menu

### ISSUE THREAD

**Issue by jecisc** [pharo-ide/Commander#20]
The class CmdOpenFamilyBookCommand add an entry on the world menu. This is present on Pharo 7. This is not the best place for an example ;)

**Comment by jecisc** [comment]
![image](https://user-images.githubusercontent.com/9519971/37117515-c03196b0-2251-11e8-90b1-d5f425aa17d8.png)

**Comment by cdlm** [comment]
👍 I noticed that today, it's indeed strange.

Also the cmd-O-F keyboard shortcut doesn't seem to work on Mac, even though the cmd-O-B one for Calypso does (as do the playground, iceberg, etc ones)

**Comment by dionisiydk** [comment]
It means that initialisation somehow was not processed.
Execute:
```Smalltalk
CmdWorldMenuRegistration initialize
```
Now shortcut should work.

Also I checked on fresh Pharo 6: it is initialised correctly after loading
Calypso.

2018-03-16 16:28 GMT+01:00 Damien Pollet <notifications@github.com>:

**Comment by dionisiydk** [comment]
But Pharo 7 sadly have it disabled. I will look why

**Comment by dionisiydk** [comment]
fixed long time ago
